SourceForge's CVS turned out to be allergic to the .. in directory names.

diff --git a/ttf2pt1/scripts/mkrel b/ttf2pt1/scripts/mkrel
--- a/ttf2pt1/scripts/mkrel
+++ b/ttf2pt1/scripts/mkrel
@@ -43,11 +43,16 @@ release)
 	;;
 esac
 
-rm -f ../ttf2pt1-$NEWVER.tgz ../ttf2pt1-$NEWVER.zip 
-rm -rf ../ttf2pt1-$NEWVER
+cd .. || {
+	echo "mkrel: can't cd to .." >&2
+	exit 1
+}
 
-echo "cvs -z9 export $TAG -d ../ttf2pt1-$NEWVER ttf2pt1"
-cvs -z9 export $TAG -d ../ttf2pt1-$NEWVER ttf2pt1 || {
+rm -f ttf2pt1-$NEWVER.tgz ttf2pt1-$NEWVER.zip 
+rm -rf ttf2pt1-$NEWVER
+
+echo "cvs -z9 export $TAG -d ttf2pt1-$NEWVER ttf2pt1"
+cvs -z9 export $TAG -d ttf2pt1-$NEWVER ttf2pt1 || {
 	echo "mkrel: unable to export from CVS" >&2
 	echo "mkrel: check that the CVS tree is properly tagged" >&2
 	exit 1
@@ -58,7 +63,7 @@ cvs -z9 export $TAG -d ../ttf2pt1-$NEWVER ttf2pt1 || {
 (
 case "$1" in
 snapshot)
-	cd ../ttf2pt1-$NEWVER || {
+	cd ttf2pt1-$NEWVER || {
 		echo "mkrel: can't cd to ../ttf2pt1-$NEWVER" >&2
 		exit 1
 	}
@@ -77,11 +82,6 @@ snapshot)
 	;;
 esac
 )
-
-cd .. || {
-	echo "mkrel: can't cd to .." >&2
-	exit 1
-}
 
 tar czvf ttf2pt1-$NEWVER.tgz ttf2pt1-$NEWVER || {
 	echo "mkrel: can't create .tgz archive" >&2
